# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

cluster_yml = YAML.load_file(File.join(File.expand_path(File.dirname(__FILE__)), "cluster.yml"))

masters = (1..cluster_yml['nb_master']).map do |n|
	{
		:hostname => "master#{n}",
		:ip => "10.0.1.#{10+n}"
	}
end
slaves = (1..cluster_yml['nb_slave']).map do |n|
	{
		:hostname => "slave#{n}",
		:ip => "10.0.2.#{10+n}"
	}
end

def master?(name)
    return /^master/ =~ name
end

def slave?(name)
    return /^slave/ =~ name
end

$script_master = <<SCRIPT
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update
sudo apt-get -y install mesos marathon
SCRIPT

$script_slave = <<SCRIPT
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)

echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  [masters,slaves].flatten.each_with_index do |virtualmachine, i|
  	config.vm.define virtualmachine[:hostname] do |cfg|
  		cfg.vm.provider :virtualbox do |vb,override|
  			override.vm.hostname = virtualmachine[:hostname]
  			override.vm.network :private_network, :ip => virtualmachine[:ip]
  		end

  		if master?(virtualmachine[:hostname]) then
  			cfg.vm.provision "shell", inline: $script_master
  		end

  		if slave?(virtualmachine[:hostname]) then
  			cfg.vm.provision "shell", inline: $script_slave
  		end
  	end
  end
end
